/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => RunCodePlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian2 = require("obsidian");

// settings.ts
var DEFAULT_SETTINGS = {
  enabledLanguages: [
    "c",
    "cpp",
    "python",
    "python3",
    "javascript",
    "js",
    "typescript",
    "ts",
    "java",
    "go",
    "rust",
    "ruby",
    "php",
    "kotlin",
    "swift",
    "scala",
    "csharp",
    "cs",
    "lua",
    "perl",
    "haskell",
    "erlang",
    "elixir",
    "d",
    "nim",
    "crystal",
    "julia",
    "ocaml",
    "fsharp",
    "fs",
    "bash",
    "sh",
    "shell",
    "coffeescript",
    "groovy",
    "vb",
    "zig"
  ],
  showRunButton: true
};

// runButtonExtension.ts
var import_view = require("@codemirror/view");
var import_state = require("@codemirror/state");
var import_language = require("@codemirror/language");

// localRunner.ts
function canRunLocally(lang) {
  const lower = lang.toLowerCase().trim();
  return ["javascript", "js", "typescript", "ts"].includes(lower);
}
function runLocal(code) {
  const logs = [];
  const errors = [];
  const originalLog = console.log;
  const originalError = console.error;
  console.log = (...args) => {
    logs.push(args.map((a) => String(a)).join(" "));
  };
  console.error = (...args) => {
    errors.push(args.map((a) => String(a)).join(" "));
  };
  let isError = false;
  try {
    const fn = new Function(code);
    const result = fn();
    if (result !== void 0) {
      logs.push(String(result));
    }
  } catch (e) {
    errors.push(e.message || String(e));
    isError = true;
  } finally {
    console.log = originalLog;
    console.error = originalError;
  }
  let output = logs.join("\n");
  if (errors.length) {
    output += (output ? "\n" : "") + errors.join("\n");
    isError = true;
  }
  if (!output.trim()) {
    output = "(no output)";
  }
  return { text: output.trimEnd(), isError };
}

// wandboxClient.ts
var import_obsidian = require("obsidian");
var WANDBOX_LANGUAGE_MAP = {
  // C / C++
  c: { compiler: "gcc-13.2.0", options: "-std=c17 -Wall -O2" },
  cpp: { compiler: "gcc-13.2.0", options: "-std=c++20 -Wall -O2" },
  "c++": { compiler: "gcc-13.2.0", options: "-std=c++20 -Wall -O2" },
  // Systems
  rust: { compiler: "rust-1.73.0" },
  go: { compiler: "go-1.21.3" },
  zig: { compiler: "zig-0.11.0" },
  d: { compiler: "dmd-2.105.0" },
  nim: { compiler: "nim-2.0.0" },
  crystal: { compiler: "crystal-1.10.1" },
  // JVM
  java: { compiler: "openjdk-jdk-21" },
  kotlin: { compiler: "kotlin-1.9.10" },
  scala: { compiler: "scala-3.3.1" },
  groovy: { compiler: "groovy-4.0.15" },
  // .NET
  csharp: { compiler: "dotnet-7.0.401" },
  cs: { compiler: "dotnet-7.0.401" },
  fsharp: { compiler: "fsharp-7.0.401" },
  fs: { compiler: "fsharp-7.0.401" },
  vb: { compiler: "vbc-7.0.401" },
  // Scripting
  python: { compiler: "cpython-3.11.4" },
  python3: { compiler: "cpython-3.11.4" },
  ruby: { compiler: "ruby-3.2.2" },
  php: { compiler: "php-8.2.10" },
  lua: { compiler: "lua-5.4.6" },
  perl: { compiler: "perl-5.38.0" },
  bash: { compiler: "bash" },
  sh: { compiler: "bash" },
  shell: { compiler: "bash" },
  // Functional
  haskell: { compiler: "ghc-9.4.6" },
  erlang: { compiler: "erlang-26.1" },
  elixir: { compiler: "elixir-1.15.6" },
  ocaml: { compiler: "ocaml-4.14.2" },
  // Other
  swift: { compiler: "swift-5.9" },
  julia: { compiler: "julia-1.9.3" },
  coffeescript: { compiler: "coffeescript-2.7.0" }
  // JS/TS are handled locally, but we keep them here for completeness if we ever want remote
  // typescript: { compiler: "typescript-5.2.2" },
  // javascript: { compiler: "nodejs-20.8.0" },
};
var WandboxClient = class {
  resolveCompiler(lang) {
    var _a;
    const lower = lang.toLowerCase().trim();
    return (_a = WANDBOX_LANGUAGE_MAP[lower]) != null ? _a : null;
  }
  async execute(code, lang) {
    const mapped = this.resolveCompiler(lang);
    if (!mapped) {
      throw new Error(`Language "${lang}" is not supported by Wandbox backend.`);
    }
    const body = {
      code,
      compiler: mapped.compiler,
      save: false
    };
    if (mapped.options) {
      body.options = mapped.options;
    }
    const response = await (0, import_obsidian.requestUrl)({
      url: "https://wandbox.org/api/compile.json",
      method: "POST",
      headers: {
        "Content-Type": "application/json"
      },
      body: JSON.stringify(body)
    });
    if (response.status !== 200) {
      throw new Error(`Wandbox API returned ${response.status}: ${response.text}`);
    }
    return response.json;
  }
  formatOutput(result) {
    let output = "";
    let isError = false;
    if (result.compiler_output) {
      output += "[Compiler Output]\n" + result.compiler_output + "\n\n";
    }
    if (result.compiler_error) {
      output += "[Compiler Error]\n" + result.compiler_error + "\n\n";
      isError = true;
    }
    if (result.program_output) {
      output += result.program_output;
      if (!result.program_output.endsWith("\n")) {
        output += "\n";
      }
    }
    if (result.program_error) {
      output += "[Runtime Error]\n" + result.program_error + "\n";
      isError = true;
    }
    if (result.status && result.status !== "0" && result.status !== "") {
      isError = true;
    }
    if (!output.trim()) {
      output = "(no output)";
    }
    return { text: output.trimEnd(), isError };
  }
};

// runButtonExtension.ts
var RunButtonWidget = class extends import_view.WidgetType {
  constructor(lang, code, settings) {
    super();
    this.lang = lang;
    this.code = code;
    this.settings = settings;
  }
  toDOM() {
    const btn = document.createElement("button");
    btn.textContent = "\u25B6";
    btn.title = "Run code";
    btn.className = "obsidian-run-code-btn";
    btn.addEventListener("click", async () => {
      await this.runCode();
    });
    return btn;
  }
  async runCode() {
    var _a;
    const container = (_a = document.activeElement) == null ? void 0 : _a.closest(".cm-preview-code-block");
    if (!container)
      return;
    let outputEl = container.querySelector(".obsidian-run-code-output");
    if (!outputEl) {
      outputEl = document.createElement("div");
      outputEl.className = "obsidian-run-code-output";
      container.appendChild(outputEl);
    }
    outputEl.textContent = "Running...";
    outputEl.style.display = "block";
    if (canRunLocally(this.lang)) {
      const result = runLocal(this.code);
      outputEl.textContent = result.text;
      outputEl.classList.toggle("is-error", result.isError);
      return;
    }
    const client = new WandboxClient();
    try {
      const result = await client.execute(this.code, this.lang);
      const formatted = client.formatOutput(result);
      outputEl.textContent = formatted.text;
      outputEl.classList.toggle("is-error", formatted.isError);
    } catch (e) {
      outputEl.textContent = "Error: " + e.message;
      outputEl.classList.add("is-error");
    }
  }
};
function runButtonExtension(settings) {
  return import_view.ViewPlugin.fromClass(
    class {
      constructor(view) {
        this.decorations = import_view.Decoration.none;
        this.decorations = this.buildDecorations(view);
      }
      update(update) {
        if (update.docChanged || update.viewportChanged) {
          this.decorations = this.buildDecorations(update.view);
        }
      }
      buildDecorations(view) {
        if (!settings.showRunButton)
          return import_view.Decoration.none;
        const builder = new import_state.RangeSetBuilder();
        const tree = (0, import_language.syntaxTree)(view.state);
        for (const { from, to } of view.visibleRanges) {
          tree.iterate({
            from,
            to,
            enter: (node) => {
              if (node.type.name === "HyperMD-codeblock-begin") {
                const line = view.state.doc.lineAt(node.to);
                const match = line.text.match(/^```\s*(\S*)/);
                const lang = match ? match[1].trim().toLowerCase() : "";
                if (lang && settings.enabledLanguages.includes(lang)) {
                  let codeEnd = node.to;
                  let depth = 1;
                  tree.iterate({
                    from: node.to,
                    to: view.state.doc.length,
                    enter: (n) => {
                      if (n.type.name === "HyperMD-codeblock-begin")
                        depth++;
                      if (n.type.name === "HyperMD-codeblock-end") {
                        depth--;
                        if (depth === 0) {
                          codeEnd = n.from;
                          return false;
                        }
                      }
                      return void 0;
                    }
                  });
                  const codeText = view.state.doc.sliceString(node.to, codeEnd).trim();
                  const deco = import_view.Decoration.widget({
                    widget: new RunButtonWidget(lang, codeText, settings),
                    side: 1
                  });
                  builder.add(node.from, node.from, deco);
                }
              }
            }
          });
        }
        return builder.finish();
      }
    },
    {
      decorations: (v) => v.decorations
    }
  );
}

// main.ts
var RunCodePlugin = class extends import_obsidian2.Plugin {
  async onload() {
    await this.loadSettings();
    this.registerEditorExtension(runButtonExtension(this.settings));
    this.registerMarkdownPostProcessor((element, context) => {
      if (!this.settings.showRunButton)
        return;
      const codeBlocks = element.querySelectorAll("pre code");
      codeBlocks.forEach((codeEl) => {
        var _a;
        const pre = codeEl.parentElement;
        if (!pre)
          return;
        const classes = Array.from(codeEl.classList);
        const langClass = classes.find((c) => c.startsWith("language-"));
        const lang = langClass ? langClass.replace("language-", "").toLowerCase() : "";
        if (!lang || !this.settings.enabledLanguages.includes(lang))
          return;
        const wrapper = document.createElement("div");
        wrapper.className = "obsidian-run-code-block";
        (_a = pre.parentNode) == null ? void 0 : _a.insertBefore(wrapper, pre);
        wrapper.appendChild(pre);
        const btn = document.createElement("button");
        btn.textContent = "\u25B6";
        btn.title = "Run code";
        btn.className = "obsidian-run-code-btn";
        btn.addEventListener("click", async () => {
          let outputEl = wrapper.querySelector(".obsidian-run-code-output");
          if (!outputEl) {
            outputEl = document.createElement("div");
            outputEl.className = "obsidian-run-code-output";
            wrapper.appendChild(outputEl);
          }
          outputEl.textContent = "Running...";
          outputEl.style.display = "block";
          const code = codeEl.textContent || "";
          if (canRunLocally(lang)) {
            const result = runLocal(code);
            outputEl.textContent = result.text;
            outputEl.classList.toggle("is-error", result.isError);
            return;
          }
          const client = new WandboxClient();
          try {
            const result = await client.execute(code, lang);
            const formatted = client.formatOutput(result);
            outputEl.textContent = formatted.text;
            outputEl.classList.toggle("is-error", formatted.isError);
          } catch (e) {
            outputEl.textContent = "Error: " + e.message;
            outputEl.classList.add("is-error");
          }
        });
        wrapper.appendChild(btn);
      });
    });
    this.addSettingTab(new RunCodeSettingTab(this.app, this));
  }
  onunload() {
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
var RunCodeSettingTab = class extends import_obsidian2.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Run Code Settings" });
    containerEl.createEl("p", {
      text: "JavaScript/TypeScript runs locally. All other languages run remotely via Wandbox.",
      cls: "setting-item-description"
    });
    new import_obsidian2.Setting(containerEl).setName("Show run button").setDesc("Display a run button on supported code blocks.").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.showRunButton).onChange(async (value) => {
        this.plugin.settings.showRunButton = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("Enabled languages").setDesc("Comma-separated list of languages that should show the run button.").addTextArea((text) => {
      text.setValue(this.plugin.settings.enabledLanguages.join(", ")).onChange(async (value) => {
        this.plugin.settings.enabledLanguages = value.split(",").map((s) => s.trim().toLowerCase()).filter((s) => s.length > 0);
        await this.plugin.saveSettings();
      });
    });
    const supportedLangs = Object.keys(WANDBOX_LANGUAGE_MAP).sort().join(", ");
    containerEl.createEl("p", {
      text: `Wandbox supported languages: ${supportedLangs}`,
      cls: "setting-item-description"
    });
  }
};
