/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __create = Object.create;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toESM = (mod, isNodeMode, target) => (target = mod != null ? __create(__getProtoOf(mod)) : {}, __copyProps(
  // If the importer is in node compatibility mode or this is not an ESM
  // file that has been converted to a CommonJS file using a Babel-
  // compatible transform (i.e. "__esModule" has not been set), then set
  // "default" to the CommonJS "module.exports" for node compatibility.
  isNodeMode || !mod || !mod.__esModule ? __defProp(target, "default", { value: mod, enumerable: true }) : target,
  mod
));
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => RunCodePlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");

// settings.ts
var DEFAULT_SETTINGS = {
  showRunButton: true,
  workspacePath: ""
};

// runButtonExtension.ts
var import_view = require("@codemirror/view");
var import_state = require("@codemirror/state");
var import_language = require("@codemirror/language");

// cppRunner.ts
var import_child_process = require("child_process");
var import_util = require("util");
var fs = __toESM(require("fs"));
var path = __toESM(require("path"));
var execFileAsync = (0, import_util.promisify)(import_child_process.execFile);
var cachedGppPath = null;
function findGpp() {
  if (cachedGppPath)
    return cachedGppPath;
  const candidates = [
    "g++",
    "C:\\msys64\\ucrt64\\bin\\g++.exe",
    "C:\\msys64\\mingw64\\bin\\g++.exe",
    "C:\\mingw64\\bin\\g++.exe"
  ];
  for (const c of candidates) {
    if (c === "g++") {
      try {
        const { execSync } = require("child_process");
        execSync("g++ --version", { stdio: "ignore" });
        cachedGppPath = c;
        return c;
      } catch (e) {
      }
    } else if (fs.existsSync(c)) {
      cachedGppPath = c;
      return c;
    }
  }
  cachedGppPath = "g++";
  return cachedGppPath;
}
function getDefaultWorkspacePath(vaultBasePath) {
  return path.join(vaultBasePath, "workspace", "run-code");
}
async function runCpp(code, workspacePath) {
  if (!fs.existsSync(workspacePath)) {
    fs.mkdirSync(workspacePath, { recursive: true });
  }
  const timestamp = Date.now();
  const srcFile = path.join(workspacePath, `tmp_${timestamp}.cpp`);
  const exeFile = path.join(workspacePath, `tmp_${timestamp}.exe`);
  fs.writeFileSync(srcFile, code, "utf-8");
  const gpp = findGpp();
  try {
    try {
      await execFileAsync(gpp, [srcFile, "-o", exeFile, "-std=c++20", "-Wall", "-O2"], {
        cwd: workspacePath,
        timeout: 3e4,
        windowsHide: true
      });
    } catch (compileErr) {
      const stderr = compileErr.stderr || compileErr.message || "";
      return { text: `[Compile Error]
${stderr}`, isError: true };
    }
    try {
      const { stdout, stderr } = await execFileAsync(exeFile, [], {
        cwd: workspacePath,
        timeout: 1e4,
        windowsHide: true
      });
      let output = stdout || "";
      if (stderr) {
        output += (output ? "\n" : "") + "[Runtime Error]\n" + stderr;
      }
      if (!output.trim())
        output = "(no output)";
      return { text: output.trimEnd(), isError: false };
    } catch (runErr) {
      let output = runErr.stdout || "";
      const stderr = runErr.stderr || "";
      if (stderr)
        output += (output ? "\n" : "") + "[Runtime Error]\n" + stderr;
      if (runErr.signal === "SIGTERM" || runErr.killed) {
        output += (output ? "\n" : "") + "(killed: timeout)";
      }
      if (!output.trim())
        output = runErr.message || "(execution failed)";
      return { text: output.trimEnd(), isError: true };
    }
  } finally {
    try {
      if (fs.existsSync(srcFile))
        fs.unlinkSync(srcFile);
    } catch (e) {
    }
    try {
      if (fs.existsSync(exeFile))
        fs.unlinkSync(exeFile);
    } catch (e) {
    }
  }
}

// runButtonExtension.ts
var RunButtonWidget = class extends import_view.WidgetType {
  constructor(code, settings) {
    super();
    this.code = code;
    this.settings = settings;
  }
  toDOM() {
    const btn = document.createElement("button");
    btn.textContent = "\u25B6";
    btn.title = "Run C++";
    btn.className = "obsidian-run-code-btn";
    btn.addEventListener("click", async () => {
      await this.runCode();
    });
    return btn;
  }
  async runCode() {
    var _a;
    const container = (_a = document.activeElement) == null ? void 0 : _a.closest(".cm-preview-code-block");
    if (!container)
      return;
    let outputEl = container.querySelector(".obsidian-run-code-output");
    if (!outputEl) {
      outputEl = document.createElement("div");
      outputEl.className = "obsidian-run-code-output";
      container.appendChild(outputEl);
    }
    outputEl.textContent = "Running...";
    outputEl.style.display = "block";
    const result = await runCpp(this.code, this.settings.workspacePath);
    outputEl.textContent = result.text;
    outputEl.classList.toggle("is-error", result.isError);
  }
};
function runButtonExtension(settings) {
  return import_view.ViewPlugin.fromClass(
    class {
      constructor(view) {
        this.decorations = import_view.Decoration.none;
        this.decorations = this.buildDecorations(view);
      }
      update(update) {
        if (update.docChanged || update.viewportChanged) {
          this.decorations = this.buildDecorations(update.view);
        }
      }
      buildDecorations(view) {
        if (!settings.showRunButton)
          return import_view.Decoration.none;
        const builder = new import_state.RangeSetBuilder();
        const tree = (0, import_language.syntaxTree)(view.state);
        for (const { from, to } of view.visibleRanges) {
          tree.iterate({
            from,
            to,
            enter: (node) => {
              if (node.type.name === "HyperMD-codeblock-begin") {
                const line = view.state.doc.lineAt(node.to);
                const match = line.text.match(/^```\s*(\S*)/);
                const lang = match ? match[1].trim().toLowerCase() : "";
                if (lang === "cpp") {
                  let codeEnd = node.to;
                  let depth = 1;
                  tree.iterate({
                    from: node.to,
                    to: view.state.doc.length,
                    enter: (n) => {
                      if (n.type.name === "HyperMD-codeblock-begin")
                        depth++;
                      if (n.type.name === "HyperMD-codeblock-end") {
                        depth--;
                        if (depth === 0) {
                          codeEnd = n.from;
                          return false;
                        }
                      }
                      return void 0;
                    }
                  });
                  const codeText = view.state.doc.sliceString(node.to, codeEnd).trim();
                  const deco = import_view.Decoration.widget({
                    widget: new RunButtonWidget(codeText, settings),
                    side: 1
                  });
                  builder.add(node.from, node.from, deco);
                }
              }
            }
          });
        }
        return builder.finish();
      }
    },
    {
      decorations: (v) => v.decorations
    }
  );
}

// main.ts
var CPP_SNIPPET = "```cpp\n#include <iostream>\n\nint main() {\n    \n    return 0;\n}\n```\n";
var RunCodePlugin = class extends import_obsidian.Plugin {
  async onload() {
    await this.loadSettings();
    if (!this.settings.workspacePath) {
      const basePath = this.app.vault.adapter.basePath;
      this.settings.workspacePath = getDefaultWorkspacePath(basePath);
    }
    this.registerEditorExtension(runButtonExtension(this.settings));
    this.registerMarkdownPostProcessor((element, context) => {
      if (!this.settings.showRunButton)
        return;
      const codeBlocks = element.querySelectorAll("pre code");
      codeBlocks.forEach((codeEl) => {
        var _a;
        const pre = codeEl.parentElement;
        if (!pre)
          return;
        const classes = Array.from(codeEl.classList);
        const langClass = classes.find((c) => c.startsWith("language-"));
        const lang = langClass ? langClass.replace("language-", "").toLowerCase() : "";
        if (lang !== "cpp")
          return;
        const wrapper = document.createElement("div");
        wrapper.className = "obsidian-run-code-block";
        (_a = pre.parentNode) == null ? void 0 : _a.insertBefore(wrapper, pre);
        wrapper.appendChild(pre);
        const btn = document.createElement("button");
        btn.textContent = "\u25B6";
        btn.title = "Run C++";
        btn.className = "obsidian-run-code-btn";
        btn.addEventListener("click", async () => {
          let outputEl = wrapper.querySelector(".obsidian-run-code-output");
          if (!outputEl) {
            outputEl = document.createElement("div");
            outputEl.className = "obsidian-run-code-output";
            wrapper.appendChild(outputEl);
          }
          outputEl.textContent = "Running...";
          outputEl.style.display = "block";
          const code = codeEl.textContent || "";
          const result = await runCpp(code, this.settings.workspacePath);
          outputEl.textContent = result.text;
          outputEl.classList.toggle("is-error", result.isError);
        });
        wrapper.appendChild(btn);
      });
    });
    this.addCommand({
      id: "insert-cpp-snippet",
      name: "Insert C++ snippet",
      editorCallback: (editor, view) => {
        const cursor = editor.getCursor();
        editor.replaceRange(CPP_SNIPPET, cursor);
        const newCursor = { line: cursor.line + 4, ch: 4 };
        editor.setCursor(newCursor);
      }
    });
    this.addSettingTab(new RunCodeSettingTab(this.app, this));
  }
  onunload() {
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
var RunCodeSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Run Code Settings" });
    containerEl.createEl("p", {
      text: "C++ code runs locally with g++. Make sure g++ is installed and accessible.",
      cls: "setting-item-description"
    });
    new import_obsidian.Setting(containerEl).setName("Show run button").setDesc("Display a run button on C++ code blocks.").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.showRunButton).onChange(async (value) => {
        this.plugin.settings.showRunButton = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Workspace path").setDesc("Directory for temporary compile files. Default: vault/workspace/run-code/").addText((text) => {
      const basePath = this.app.vault.adapter.basePath;
      const defaultPath = getDefaultWorkspacePath(basePath);
      text.setPlaceholder("Auto").setValue(
        this.plugin.settings.workspacePath === defaultPath ? "" : this.plugin.settings.workspacePath
      ).onChange(async (value) => {
        this.plugin.settings.workspacePath = value.trim() || defaultPath;
        await this.plugin.saveSettings();
      });
    });
  }
};
