// Main entry point - Generated by Source Forest Generator
// Solution: @SOLUTION_NAME@

#include <iostream>

// Forward declarations for module initialization
@FORWARD_DECLS@

int main() {
    std::cout << "========================================" << std::endl;
    std::cout << "  @SOLUTION_NAME@ - Source Forest Demo" << std::endl;
    std::cout << "========================================" << std::endl;
    std::cout << std::endl;
    
    std::cout << "[Main] Initializing modules..." << std::endl;
@INIT_CALLS@
    
    std::cout << std::endl << "========================================" << std::endl;
    std::cout << "  All modules initialized successfully!" << std::endl;
    std::cout << "========================================" << std::endl;
    
    return 0;
}
